// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package io.ntr;

public final class NtrProtos {
    private NtrProtos() {
    }

    public static void registerAllExtensions(
                                             com.google.protobuf.ExtensionRegistryLite registry) {
        registry.add(io.ntr.NtrProtos.topic);
        registry.add(io.ntr.NtrProtos.event);
    }

    public static void registerAllExtensions(
                                             com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface EventOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ntr.event.Event)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string event_name = 1;</code>
         */
        java.lang.String getEventName();

        /**
         * <code>string event_name = 1;</code>
         */
        com.google.protobuf.ByteString getEventNameBytes();

        /**
         * <code>string inner_type_name = 2;</code>
         */
        java.lang.String getInnerTypeName();

        /**
         * <code>string inner_type_name = 2;</code>
         */
        com.google.protobuf.ByteString getInnerTypeNameBytes();

        /**
         * <code>.google.protobuf.Any data = 101;</code>
         */
        boolean hasData();

        /**
         * <code>.google.protobuf.Any data = 101;</code>
         */
        com.google.protobuf.Any getData();

        /**
         * <code>.google.protobuf.Any data = 101;</code>
         */
        com.google.protobuf.AnyOrBuilder getDataOrBuilder();
    }

    /**
     * <pre>
     * A single event published in a topic.
     * </pre>
     *
     * Protobuf type {@code ntr.event.Event}
     */
    public static final class Event extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ntr.event.Event)
            EventOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Event.newBuilder() to construct.
        private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Event() {
            eventName_ = "";
            innerTypeName_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Event(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            eventName_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            innerTypeName_ = s;
                            break;
                        }
                        case 810: {
                            com.google.protobuf.Any.Builder subBuilder = null;
                            if (data_ != null) {
                                subBuilder = data_.toBuilder();
                            }
                            data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(data_);
                                data_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            }
            catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            }
            catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            }
            finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return io.ntr.NtrProtos.internal_static_ntr_event_Event_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return io.ntr.NtrProtos.internal_static_ntr_event_Event_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.ntr.NtrProtos.Event.class, io.ntr.NtrProtos.Event.Builder.class);
        }

        public static final int EVENT_NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object eventName_;

        /**
         * <code>string event_name = 1;</code>
         */
        public java.lang.String getEventName() {
            java.lang.Object ref = eventName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                eventName_ = s;
                return s;
            }
        }

        /**
         * <code>string event_name = 1;</code>
         */
        public com.google.protobuf.ByteString getEventNameBytes() {
            java.lang.Object ref = eventName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                eventName_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int INNER_TYPE_NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object innerTypeName_;

        /**
         * <code>string inner_type_name = 2;</code>
         */
        public java.lang.String getInnerTypeName() {
            java.lang.Object ref = innerTypeName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                innerTypeName_ = s;
                return s;
            }
        }

        /**
         * <code>string inner_type_name = 2;</code>
         */
        public com.google.protobuf.ByteString getInnerTypeNameBytes() {
            java.lang.Object ref = innerTypeName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                innerTypeName_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DATA_FIELD_NUMBER = 101;
        private com.google.protobuf.Any data_;

        /**
         * <code>.google.protobuf.Any data = 101;</code>
         */
        public boolean hasData() {
            return data_ != null;
        }

        /**
         * <code>.google.protobuf.Any data = 101;</code>
         */
        public com.google.protobuf.Any getData() {
            return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        }

        /**
         * <code>.google.protobuf.Any data = 101;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
            return getData();
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getEventNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventName_);
            }
            if (!getInnerTypeNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, innerTypeName_);
            }
            if (data_ != null) {
                output.writeMessage(101, getData());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!getEventNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventName_);
            }
            if (!getInnerTypeNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, innerTypeName_);
            }
            if (data_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(101, getData());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.ntr.NtrProtos.Event)) {
                return super.equals(obj);
            }
            io.ntr.NtrProtos.Event other = (io.ntr.NtrProtos.Event) obj;

            boolean result = true;
            result = result && getEventName()
                    .equals(other.getEventName());
            result = result && getInnerTypeName()
                    .equals(other.getInnerTypeName());
            result = result && (hasData() == other.hasData());
            if (hasData()) {
                result = result && getData()
                        .equals(other.getData());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getEventName().hashCode();
            hash = (37 * hash) + INNER_TYPE_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getInnerTypeName().hashCode();
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       java.nio.ByteBuffer data,
                                                       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       com.google.protobuf.ByteString data,
                                                       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.ntr.NtrProtos.Event parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       byte[] data,
                                                       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.ntr.NtrProtos.Event parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       java.io.InputStream input,
                                                       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.ntr.NtrProtos.Event parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.ntr.NtrProtos.Event parseDelimitedFrom(
                                                                java.io.InputStream input,
                                                                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.ntr.NtrProtos.Event parseFrom(
                                                       com.google.protobuf.CodedInputStream input,
                                                       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.ntr.NtrProtos.Event prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                                            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * A single event published in a topic.
         * </pre>
         *
         * Protobuf type {@code ntr.event.Event}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ntr.event.Event)
                io.ntr.NtrProtos.EventOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return io.ntr.NtrProtos.internal_static_ntr_event_Event_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return io.ntr.NtrProtos.internal_static_ntr_event_Event_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.ntr.NtrProtos.Event.class, io.ntr.NtrProtos.Event.Builder.class);
            }

            // Construct using io.ntr.NtrProtos.Event.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                eventName_ = "";

                innerTypeName_ = "";

                if (dataBuilder_ == null) {
                    data_ = null;
                }
                else {
                    data_ = null;
                    dataBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return io.ntr.NtrProtos.internal_static_ntr_event_Event_descriptor;
            }

            @java.lang.Override
            public io.ntr.NtrProtos.Event getDefaultInstanceForType() {
                return io.ntr.NtrProtos.Event.getDefaultInstance();
            }

            @java.lang.Override
            public io.ntr.NtrProtos.Event build() {
                io.ntr.NtrProtos.Event result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.ntr.NtrProtos.Event buildPartial() {
                io.ntr.NtrProtos.Event result = new io.ntr.NtrProtos.Event(this);
                result.eventName_ = eventName_;
                result.innerTypeName_ = innerTypeName_;
                if (dataBuilder_ == null) {
                    result.data_ = data_;
                }
                else {
                    result.data_ = dataBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                                    com.google.protobuf.Descriptors.FieldDescriptor field,
                                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                                      com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                                      com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                                            com.google.protobuf.Descriptors.FieldDescriptor field,
                                            int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                                            com.google.protobuf.Descriptors.FieldDescriptor field,
                                            java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.ntr.NtrProtos.Event) {
                    return mergeFrom((io.ntr.NtrProtos.Event) other);
                }
                else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.ntr.NtrProtos.Event other) {
                if (other == io.ntr.NtrProtos.Event.getDefaultInstance())
                    return this;
                if (!other.getEventName().isEmpty()) {
                    eventName_ = other.eventName_;
                    onChanged();
                }
                if (!other.getInnerTypeName().isEmpty()) {
                    innerTypeName_ = other.innerTypeName_;
                    onChanged();
                }
                if (other.hasData()) {
                    mergeData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                                     com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.ntr.NtrProtos.Event parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                }
                catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.ntr.NtrProtos.Event) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                }
                finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object eventName_ = "";

            /**
             * <code>string event_name = 1;</code>
             */
            public java.lang.String getEventName() {
                java.lang.Object ref = eventName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    eventName_ = s;
                    return s;
                }
                else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string event_name = 1;</code>
             */
            public com.google.protobuf.ByteString getEventNameBytes() {
                java.lang.Object ref = eventName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    eventName_ = b;
                    return b;
                }
                else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string event_name = 1;</code>
             */
            public Builder setEventName(
                                        java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                eventName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string event_name = 1;</code>
             */
            public Builder clearEventName() {

                eventName_ = getDefaultInstance().getEventName();
                onChanged();
                return this;
            }

            /**
             * <code>string event_name = 1;</code>
             */
            public Builder setEventNameBytes(
                                             com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                eventName_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object innerTypeName_ = "";

            /**
             * <code>string inner_type_name = 2;</code>
             */
            public java.lang.String getInnerTypeName() {
                java.lang.Object ref = innerTypeName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    innerTypeName_ = s;
                    return s;
                }
                else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string inner_type_name = 2;</code>
             */
            public com.google.protobuf.ByteString getInnerTypeNameBytes() {
                java.lang.Object ref = innerTypeName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    innerTypeName_ = b;
                    return b;
                }
                else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string inner_type_name = 2;</code>
             */
            public Builder setInnerTypeName(
                                            java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                innerTypeName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string inner_type_name = 2;</code>
             */
            public Builder clearInnerTypeName() {

                innerTypeName_ = getDefaultInstance().getInnerTypeName();
                onChanged();
                return this;
            }

            /**
             * <code>string inner_type_name = 2;</code>
             */
            public Builder setInnerTypeNameBytes(
                                                 com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                innerTypeName_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.Any data_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public boolean hasData() {
                return dataBuilder_ != null || data_ != null;
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public com.google.protobuf.Any getData() {
                if (dataBuilder_ == null) {
                    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
                }
                else {
                    return dataBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public Builder setData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    data_ = value;
                    onChanged();
                }
                else {
                    dataBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public Builder setData(
                                   com.google.protobuf.Any.Builder builderForValue) {
                if (dataBuilder_ == null) {
                    data_ = builderForValue.build();
                    onChanged();
                }
                else {
                    dataBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public Builder mergeData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (data_ != null) {
                        data_ = com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
                    }
                    else {
                        data_ = value;
                    }
                    onChanged();
                }
                else {
                    dataBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public Builder clearData() {
                if (dataBuilder_ == null) {
                    data_ = null;
                    onChanged();
                }
                else {
                    data_ = null;
                    dataBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public com.google.protobuf.Any.Builder getDataBuilder() {

                onChanged();
                return getDataFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
                if (dataBuilder_ != null) {
                    return dataBuilder_.getMessageOrBuilder();
                }
                else {
                    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
                }
            }

            /**
             * <code>.google.protobuf.Any data = 101;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> getDataFieldBuilder() {
                if (dataBuilder_ == null) {
                    dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getData(),
                            getParentForChildren(),
                            isClean());
                    data_ = null;
                }
                return dataBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                                                  final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                                                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:ntr.event.Event)
        }

        // @@protoc_insertion_point(class_scope:ntr.event.Event)
        private static final io.ntr.NtrProtos.Event DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new io.ntr.NtrProtos.Event();
        }

        public static io.ntr.NtrProtos.Event getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Event> PARSER = new com.google.protobuf.AbstractParser<Event>() {
            @java.lang.Override
            public Event parsePartialFrom(
                                          com.google.protobuf.CodedInputStream input,
                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Event(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Event> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Event> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.ntr.NtrProtos.Event getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public static final int TOPIC_FIELD_NUMBER = 50001;
    /**
     * <pre>
     * Event topic
     * </pre>
     *
     * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
     */
    public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<com.google.protobuf.DescriptorProtos.EnumValueOptions, java.lang.String> topic = com.google.protobuf.GeneratedMessage
            .newFileScopedGeneratedExtension(
                    java.lang.String.class,
                    null);
    public static final int EVENT_FIELD_NUMBER = 50002;
    /**
     * <pre>
     * Event name/type
     * </pre>
     *
     * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
     */
    public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<com.google.protobuf.DescriptorProtos.EnumValueOptions, java.lang.String> event = com.google.protobuf.GeneratedMessage
            .newFileScopedGeneratedExtension(
                    java.lang.String.class,
                    null);
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_ntr_event_Event_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_ntr_event_Event_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\013event.proto\022\tntr.event\032\031google/protobu" +
                        "f/any.proto\032 google/protobuf/descriptor." +
                        "proto\"^\n\005Event\022\022\n\nevent_name\030\001 \001(\t\022\027\n\017in" +
                        "ner_type_name\030\002 \001(\t\022\"\n\004data\030e \001(\0132\024.goog" +
                        "le.protobuf.AnyJ\004\010\003\020\007:2\n\005topic\022!.google." +
                        "protobuf.EnumValueOptions\030\321\206\003 \001(\t:2\n\005eve" +
                        "nt\022!.google.protobuf.EnumValueOptions\030\322\206" +
                        "\003 \001(\tB\023\n\006io.ntrB\tNtrProtosb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                                                                           com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                                com.google.protobuf.DescriptorProtos.getDescriptor(),
                        }, assigner);
        internal_static_ntr_event_Event_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_ntr_event_Event_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ntr_event_Event_descriptor,
                new java.lang.String[]{ "EventName", "InnerTypeName", "Data", });
        topic.internalInit(descriptor.getExtensions().get(0));
        event.internalInit(descriptor.getExtensions().get(1));
        com.google.protobuf.AnyProto.getDescriptor();
        com.google.protobuf.DescriptorProtos.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
